apiVersion: v1
kind: Namespace
metadata:
  name: dev-kpe
  labels:
    app: dev-kpe
    name: dev-kpe
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: dev-kpe
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 0.5
    defaultRequest:
      memory: 256Mi
      cpu: 0.2
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: doscont
  namespace: dev-kpe
spec:
 containers:
 - name: cont1
   image: python:3.6-alpine
   command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8082']

