apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend
  labels:
    app: backend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-nginx
  template:
    metadata:
      labels:
        app: backend-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-backed
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend-nginx 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 
