apiVersion: v1
kind: Pod
metadata:
  name: nginxsa1
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginxsa2
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80