apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
stringData:
  username: Pruebas
  password: PruebasPWD
---

apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: nginx:alpine
    env:
      - name: USERTEST
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: username
            optional: false # same as default; "mysecret" must exist
                            # and include a key named "username"
      - name: PASSWORDTEST
        valueFrom:
          secretKeyRef:
            name: mysecret2
            key: password
            optional: false # same as default; "mysecret" must exist
                            # and include a key named "password"
  restartPolicy: Never