apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backed-hand-on
  labels:
    app: go-backend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: javing77/k8s-hands-on-golang
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: go-backed-hand-on
  labels:
    app: go-backend
spec:
  selector:
    app: go-backend 
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090 
