---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-kpe
  labels:
    app: dev-kpe
    name: dev-kpe
---
apiVersion: v1
kind: Namespace
metadata:
  name: pro-kpe
  labels:
    app: pro-kpe
    name: pro-kpe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-kpe
  name: go-backed-hand-dev
  labels:
    app: go-backend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: javing77/k8s-hands-on-golang
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pro-kpe
  name: go-backed-hand-pro
  labels:
    app: go-backend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
      - name: go-backend
        image: javing77/k8s-hands-on-golang
        imagePullPolicy: IfNotPresent