apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1Z6Q0NBVDhDQVFBd0VqRVFNQTRHQTFVRUF3d0hjM1IxWkdWdWREQ0NBU0l3RFFZSktvWklodmNOQVFFQgpCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOOUQrRDZvalhJanpnZHdSbS9IdW00UGlwS2VqZFAzUkFReDNpd2pTaUc4ClVaR1cxb3BjZ24yczNVSkZLSDFTSWczcGpVN1N3VUNEVlMrQmxyWUoyQVRWMTBJM3VrRnl4UGtVWkJaWmxZVFMKYjhXbzFBRjJZNVJ6NVI3YkVTb2pnOUN1cVcxYWN5ejNOdUc1TndwQVBmS1hraFJGYVQ5Y3U1Q3BnTFFXaUZFRQpJbkxxL2RhQkVRUGVzaVlkMG40OW80S1NISWQ4RVc0Q3pRbmpBc0VvSlJlSFNzTWhaNkdwOWxzZkZGSVV0cnFNCkdqMXdtOWJvT1pZdHp6WSttVTZuOHlNTjhIYzJaVXd0ZzJqZVE1NzVPK0RtNTN4TkxTVWVPL2Q4eG83aldBWEYKWFRJWWRoOCtoc3dIbVY5T3h6ZGRaOUV1cGFIOG9oTDlLdGd2Zy9VOVNZc0NBd0VBQWFBQU1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUMzUDE0UmJhNUxYSE1ubW9VTWFTdEhBcTk3dVZESzIvbGxCSzN5QjF6Z3llTGYzc2xjCjNVQ3lrQWp1VmwrODF2RUw4dk95K0VQeEhxVUFwMWNRU2UvbWxselFKenMrT21UYTVvZ0ZMbVZ1b242M1g5eGkKV0ZCeVpGVWJ5U2YwK1BHZllNM0pJRXVuVUYvTEhCRW1QMStiTUpsL29wRmdKWU1pSVNROUhOeE9sYlFYVjM0eQpUSCs2ZW1WQTNKUW9KVlRsNHBoNnI4a09URHIzN3owZE81UGx1QkxuaXNWc1pxdmIycWJiOTR6WjFnT3NCTm55Cm93VXU5WTlsSjlXMitDUDNnZWJIMWxiSnpUQ29nRENadzVBUGxuY09nYjFNOGNvb0d5TjhrdzQwQ2pqRWNvb0IKR0N5RlVXY1F2OXlUcnozenQwTWZ4MFpNNkcyYXZFTk9HS1J2Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo= 
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
