apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-frontend-3
  labels:
    app: guestbook2
spec:
  # modifica las réplicas según tu caso de uso
  replicas: 3
  selector:
    matchLabels:
      tier: frontend3
  # Desde este pundo inica la configuracion del pod
  template:
    metadata:
      labels:
        tier: frontend3
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3


