apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-frontend-2
  labels:
    app: guestbook2
    tier: frontend
spec:
  # modifica las réplicas según tu caso de uso
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  # Desde este pundo inica la configuracion del pod
  template:
    metadata:
      labels:
        run: pruebapod1
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3


